### ISSUE TITLE
Om denne spesifikasjonen bør settes som "utgått"

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/kvalitet-pa-datasett#3]
Det er utarbeidet et [utkast til DQV-AP-NO](https://informasjonsforvaltning.github.io/dqv-ap-no/) som sammen med DCAT-AP-NO implementerer forslagene i denne spesifikasjonen. 

DQV-AP-NO supplerer DCAT-AP-NO, og begge er p.t. på høring (med høringsfrist 2020-09-01). 

Etter revisjon av DCAT-AP-NO bør det vurderes om denne spesifikasjonen kan settes som "utgått" og erstattet av DQV-AP-NO.

**Comment by KjerstiSteien** [comment]
@jimjyang utfra det jeg kan se, ser det ut til at denne er løst. Stemmer det?

**Comment by jimjyang** [comment]
Ja, løst. 
Lukkes.
